Adding the state-of-the-state dataset
rudeboybert/fivethirtyeight pull request #56
Opened 2019-11-08 23:01 UTC by mariumtapal

Adding the cleaned and documented state-of-the-state dataset to the fivethirtyeight package

2019-11-09 15:09 UTC, beanumber requested changes

2019-11-09 15:09 UTC, beanumber commented on R/data_marium.R
> +#' What America’s Governors Are Talking About
Can @mariumtapal please use the `@rdname` directive to document these two data sets in the same article?

2019-11-09 15:09 UTC, beanumber commented on R/data_marium.R
> +#' What America’s Governors Are Talking About
Please also add yourself as a contributor in the `DESCRIPTION` file and the `NEWS.md`

2019-11-10 13:35 UTC, rudeboybert commented
Hey @mariumtapal, thanks for this PR. 

On top of Ben's suggestions, a couple of notes:

No 1: the data set names `index` and `words` are a little too generic. In fact, the object name `words` clashes with `stringr::words`. Could you rename these `state_index` and `state_words`?

No 2: If you look at the top of this PR #56 page, you'll see that your commits are tagged with a grey image of the GitHub OctoCat, and not your GitHub profile image:

<img width="553" alt="Screen Shot 2019-11-10 at 8 26 57 AM" src="https://user-images.githubusercontent.com/4574203/68544699-fa249a00-0393-11ea-8897-7664c8c20405.png">

While seemingly innocuous, @Starryz and I discovered that if you don't fix this, your contributions to the package will not be listed on the repo's [contributors page](https://github.com/rudeboybert/fivethirtyeight/graphs/contributors). Please
* Follow the ["In your terminal, copy each line and change the Github username and Github registering..."](https://github.com/rudeboybert/fivethirtyeight/wiki/Instructions-on-how-to-add-a-new-dataset) steps in the Wiki to fix this
* Copy your work in `data-raw/process_data_marium.R` and `R/data_marium.R` somewhere else
* Delete the repo, and start the entire forking/cloning process over but using the above two files
* Create a new PR

This way your work will be fully credited on the [contributors page](https://github.com/rudeboybert/fivethirtyeight/graphs/contributors)

2019-11-12 21:20 UTC, closed without merging