initial commit
rudeboybert/fivethirtyeight pull request #6
Opened 2017-02-24 16:58 UTC by jonathanbouchet

Hi,
these are the files for the analysis of the 538 dataset (based on my Kaggle's kernel)
Files : Rmarkdown for quick analysis and visualization ; R file : raw code

thanks,
Jonathan

2017-02-24 17:09 UTC, jonathanbouchet commented
there is an error during the pull-request about the `fmsb` package (radarchart) not found

2017-02-24 17:14 UTC, rudeboybert commented
Don't worry about this. I'll thread things together this weekend and write back if I have comments! Thanks for the pull request!

2017-02-27 19:15 UTC, rudeboybert requested changes
Thanks for your pull request. The substance of your work looks great, but we have a few comments regarding more cosmetic style issues.

Our main target demographic for these vignettes are undergraduate students. As such we try to stay very consistent when it comes to style/formatting so as to not confuse them. Your "overview plot" code looks great, but then things get a little hard to read in "Number of Characters vs. Time." 

Could you address our comments and let us know when you've done so? Also note that I made comments on the `.R` file instead of the `.Rmd` file by accident. Apologies for this.

thanks

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +percent_gen_pub <- percent_gen_pub %>%
could you merge all these into a single chain?

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +  mutate(percentage = 100*number/countT) %>%
Could you merge into a single mutate?
```
mutate(
  percentage = 100*number/countT),
  label = paste0(round(percentage, 2))
) %>%
```

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +  ggplot(aes(x = publisher, y = number, fill = publisher)) +
Could save data frame to one object and save ggplot object to another? We try to avoid piping directly into `ggplot()`

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +marvel_vs_time <- as.data.frame(comic_characters %>%
* Is the `as.data.frame()` necessary? I got code working without it
* Are you working in RStudio? You can auto-reindent lines by selecting and pressing CTRL+I

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +marvel_vs_time$sex <- factor(marvel_vs_time$sex, levels = c("Female Characters", "Male Characters", "Genderfluid Characters","Agender Characters"))
Could you have lines 41-42 be part of above dplyr chain using `mutate`?

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +dc_vs_time <- as.data.frame(comic_characters %>% filter(publisher == 'DC' & !is.na(month) & !is.na(sex)))
Please combine lines 47-52 into a single dplyr chain using `mutate`s

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +dc_vs_time$sex <- factor(dc_vs_time$sex, levels = c("Female Characters", "Male Characters", "Genderless Characters","Transgender Characters"))
You have `c("Female Characters", "Male Characters", "Genderless Characters","Transgender Characters")` a few times throughout your code. How about assigning this to a variable so as to not repeat yourself?

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +	currentFeature[[i]] <- as.data.frame(comic_characters %>%
See note above about `as.data.frame()` and reindenting

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +g2 <- ggplot(data = dc_vs_time, aes(year, ordered_month)) + geom_tile(aes(fill = number),colour = "white") +
For all `ggplot()` calls, could you have each layer on its own line? i.e.
```
ggplot(data = dc_vs_time, aes(year, ordered_month)) + 
  geom_tile(aes(fill = number),colour = "white") + 
  scale_fill_gradient(low = "#3B9AB2", high = "black") + 
```

2017-02-27 19:15 UTC, rudeboybert commented on vignettes/comics_gender.R
> +merged <- merge(aggregateFeature('DC','hair')[[1]], aggregateFeature('Marvel','hair')[[1]], by='hair', all=TRUE)
could you use a `dplyr` `join` instead of `merge`?

2017-02-28 01:50 UTC, jonathanbouchet commented
thanks for the comments and advices. Having a single mutate is indeed much cleaner.
I have added my changes to my fork-repo but I may have messed with the commit history since you have updated the repo since. 

Also I'm not sure my changes are updated in the pull-request. 
Please let me know if you see them.

thanks

2017-02-28 13:05 UTC, merged

2017-02-28 13:06 UTC, rudeboybert commented
Everything looks great; thanks for updating. Merged

2017-02-28 13:18 UTC, rudeboybert commented
You're now on the list of [contributors](https://github.com/rudeboybert/fivethirtyeight/graphs/contributors) on GitHub!

2017-02-28 13:38 UTC, jonathanbouchet commented
thanks !