Irene Ryan pull request for riddler castle datasets
rudeboybert/fivethirtyeight pull request #72
Opened 2019-11-19 20:06 UTC by ireneryan

2019-11-19 20:28 UTC, beanumber requested changes

2019-11-19 20:28 UTC, beanumber commented on DESCRIPTION
> +    person("Irene", "Ryan", email = "ryan.irene3@gmail.com", role = "ctb"))
You've got a trailing parenthesis here that needs to be replaced with a comma

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +library(tidyverse)
This file needs to be in `data-raw/`, not at the root level of the repository.

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +castle_solutions<-castle_solutions%>% #clean the names
Please put spaces around `<-` and `%>%` throughout this code.

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +colnames(castle_solutions)[11] <- "strategy"
Can you replace the hard-coded index here with a call to `dplyr::rename()`?

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +castle_solutions<-gather(castle_solutions, key = "castle", value = "number_of_soldiers", castle_1, castle_2, castle_3, castle_4, castle_5, castle_6,
Please add carriage returns so that this doesn't go so far on one line

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +castle_solutions<-gather(castle_solutions, key = "castle", value = "number_of_soldiers", castle_1, castle_2, castle_3, castle_4, castle_5, castle_6,
You could also the select helper `contains("castle_")` make this a little shorter.

2019-11-19 20:28 UTC, beanumber commented on process_data_set_irene.R
> +colnames(castle_solutions_3)[11] <- "strategy"
Ditto the previous comment on hard-coding indices.

2019-11-20 03:33 UTC, beanumber requested changes

2019-11-20 03:33 UTC, beanumber commented on data-raw/process_data_set_irene.R
> +castle_solutions <- castle_solutions[c("user", "castle", "number_of_soldiers", "strategy")]
As per @rudeboybert 's preferences #61 , please use a `tidyverse` style. So here you would replace the `[` with a call to `select()`.

2019-11-20 03:33 UTC, beanumber commented on data-raw/process_data_set_irene.R
> +castle_solutions <- castle_solutions%>%
spaces before the `%>%` please! You can use `lintr` to fix these automatically if you get sick of doing it manually!

2019-11-20 03:33 UTC, beanumber commented on data-raw/process_data_set_irene.R
> +castle_solutions_2 <- castle_solutions_2[c("user", "castle", "number_of_soldiers", "strategy")]
Please use `select()`

2019-11-20 03:33 UTC, beanumber commented on data-raw/process_data_set_irene.R
> +castle_solutions_2 <- castle_solutions_2%>%
space

2019-11-20 03:33 UTC, beanumber commented on data-raw/process_data_set_irene.R
> +castle_solutions_3 <- castle_solutions_3[c("user", "castle", "number_of_soldiers", "strategy")]
ditto

2019-11-20 03:33 UTC, beanumber commented on process_data_set_irene.R
> +library(tidyverse)
You have to delete this file and then commit the deletion to get it out of here.

2019-11-20 18:18 UTC, rudeboybert approved these changes

2019-11-20 18:18 UTC, merged

2019-11-20 18:19 UTC, rudeboybert commented
Thanks @ireneryan, you're now listed as a package contributor: https://github.com/rudeboybert/fivethirtyeight/graphs/contributors